.\"
.\"  To format this reference page, use the command:
.\"
.\"    nroff -man popcheck.1
.\"
.TH POPCHECK 1 "" "" "" ""
.SH NAME
popcheck \- examine (and possibly delete) messages in a POP server mailbox
.SH SYNOPSIS
popcheck [-s \fIpop3_server\fR]
[-P \fIpop3_port\fR]
[-u \fIpop3_user\fR] [-p \fIpop3_password\fR]
[-o \fIfilename\fR]
[-i \fIfilename\fR]
.SH DESCRIPTION
.I popcheck
fetches a list of messages waiting on a POP server and allows the user to delete selected messages.
It can work interactively (default) or in batch mode
(\fI-o\fR and \fI-i\fR options).
.\"
.SH OPTIONS
The following options are available from the command line:
.PP
.TP 4
.B -s
Selects the POP mail server.
.TP
.B -P
Selects the port to connect to on the mail server.
Defaults to 110, the standard POP3 port.
.TP
.B -u
Selects the mail account on the mail server.
.TP
.B -p
Provides the password for accessing the mail account.
This is not recommended, as it makes it easy to reveal your password
to others in various ways.
If the password is not provided on the command line, the
program prompts for it.
.TP
.B -i
Run in batch mode.
Read a list of messages from specified file and tell
the POP server to delete these messages.
USE THIS OPTION CAREFULLY.
.TP
.B -o
Run in batch mode.
Store the collected information in the specified file.
.br
.\"
.SH "INTERACTIVE OPERATION"
.PP
You are presented with a list of messages and can
mark some of them for deletion.
.PP
Keys available during interactive operation:
.nf
UP, p       - Up one line
DOWN, n     - Down one line
PGUP, -     - Up one page
PGDN, space - Down one page
d           - Mark/Unmark message
s           - Exit and save changes
q           - Exit without saving anything
.fi
.sp
.SH "BATCH MODE OPERATION"
.PP
Run popcheck with the -o switch first to make a text file with all
messages, including numbers and sizes.
.PP
Edit this file and remove all lines describing mail you want to keep.
.PP
Make sure the only lines in the file are those describing the mails you
want to REMOVE.
Please double-check because there is no turning-back
after you execute popcheck with the -i switch.
.PP
Run popcheck with the -i switch.
All messages matching the message
numbers and sizes (in the file) will be removed from the POP server.

.SH CAVEATS
.PP
Please note that you run this program on your own risk.
It's very easy to remove messages that you want to remove, but also to remove messages
that you didn't want to remove.
BE CAREFUL.

.SH AUTHOR
.PP
Staffan Hamala <staham@algonet.se>
